### ISSUE TITLE
Webhook service failts to deliver big messages

### ISSUE THREAD

**Issue by destag** [fixthestatusquo/proca-server#257]
When we change campaign that has big config associated with it, the webhook service associated with it will fail.

How it works:
- We change the campaign
- `Proca.Stage.Event` is emitted to rabbitmq
- `Proca.Stage.Webhook` receives the message
- `Proca.Stage.Webhook` sends request to webhook service
- when the payload is bigger than 64KB, it fails because of `Tesla.Adapter.Mint` http2 error

The question is how should we handle that big messages?

---

Some details about last error of this kind:

```yml
message_size: 239174 bytes
x-death:	
    count: 435
    exchange: org.320.event
    queue: wrk.1.webhook
    reason: rejected
    routing-keys: system.campaign_updated
    time: 1719321465 # 2024-06-25 13:17:45+00:00
```
